### ISSUE TITLE
Annoying verbose Cypress browser console warning

### ISSUE THREAD

**Issue by Dan503** [NicholasBoll/cypress-promise#7] opened 2020-03-15 05:48 UTC
I get this really annoying warning in the browser console when I try to use async/await with promisify:

## The warning

> Cypress Warning: Cypress detected that you returned a promise in a test, but also invoked one or more cy commands inside of that promise.
> 
> The test title was:
> 
>   > element exists
> 
> While this works in practice, it's often indicative of an anti-pattern. You almost never need to return both a promise and also invoke cy commands.
> 
> Cy commands themselves are already promise like, and you can likely avoid the use of the separate Promise.
> 
> https://on.cypress.io/returning-promise-and-commands-in-test

## Reduced test case

This is my reduced test case written in Typescript:

```ts
import promisify from 'cypress-promise'

const loadTestPage = (): Promise<Window> => promisify(cy.visit('./cypress/test-file.html'))

async function runTest() {
	it('element exists', async () => {
		await loadTestPage()
		cy.get(`#element`).should('exist')
	})
}

runTest()
```

**Comment by NicholasBoll** [comment] 2020-03-27 20:40
Duplicate of #6

**Closed as completed by NicholasBoll** 2020-03-27 20:40 UTC
